update README
instructlab/eval pull request #108
Opened 2024-08-26 19:52 UTC by sallyom

a few caveats I found when running (and on rhel 9.3)

2024-08-27 14:35 UTC, danmcp requested changes

2024-08-28 12:50 UTC, sallyom commented on README.md
> +cd eval
sg, i'll update - but when I open a new shell, I'm always dropped into $HOME so I was not in eval in the 2nd shell

2024-08-28 12:50 UTC, sallyom commented on README.md
> +> **⚠️ Note:** Must use Python version 3.11 or later.
ok, that I took from a slack thread - but all I know is the default 3.9 from rhel 9.3 is too low. I'll update to 3.10

2024-08-28 12:51 UTC, sallyom commented on README.md
> +sudo systemctl start nvidia-toolkit-setup.service
probably not, I opened this b4 #2152 - I'll remove this

2024-08-28 12:55 UTC, sallyom commented on README.md
> +sudo systemctl start nvidia-toolkit-setup.service
updated

2024-08-28 12:55 UTC, sallyom commented on README.md
> +cd eval
updated to comment

2024-08-28 12:55 UTC, sallyom commented on README.md
> +> **⚠️ Note:** Must use Python version 3.11 or later.
done

2024-08-28 13:02 UTC, danmcp approved these changes

2024-08-28 13:34 UTC, nathan-weinberg approved these changes
Thanks Sally!

2024-08-28 13:34 UTC, merged