Remove remaining print()s from the library
instructlab/eval pull request #86
Opened 2024-07-31 19:31 UTC by booxter

Use logger for any messages produced instead.

2024-08-01 14:43 UTC, bcrochet approved these changes
/lgtm

2024-08-04 13:59 UTC, danmcp approved these changes

2024-08-04 17:13 UTC, danmcp requested changes
Until #80 is fixed, we probably need to make this be:

```
if i == max retires-1:
  logger.error
  break
logger.debug
```

Otherwise we won't give any indication of an invalid setup until the very end.

Note: This suggestion is taking the rebase into account since the break wouldn't make sense as is.

2024-08-05 16:07 UTC, booxter commented on src/instructlab/eval/mt_bench_common.py
> +                logger.warning(e)
maybe even `error`? (@danmcp let me know if there's a good reason to do `info`, as in your snippet.)

2024-08-05 16:28 UTC, booxter commented on src/instructlab/eval/mt_bench_common.py
> +                logger.warning(e)
I was! Will update to `error`.

2024-08-05 18:59 UTC, nathan-weinberg approved these changes
will rerun mypy check once https://github.com/instructlab/eval/pull/93 merges

2024-08-05 20:00 UTC, danmcp commented
@booxter Note I rebased your commit to pull in #93

2024-08-05 20:00 UTC, danmcp approved these changes

2024-08-05 20:48 UTC, merged